[package]
name = "http-request-test"
version = "0.1.0"
authors = ["dmitriipetrishin"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.3", features = ["blocking", "json"] }
tokio = "0.2.12"
